# Generated by Django 5.2.3 on 2025-07-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_checkout_url_payment_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Checkout URL"
            ),
        ),
    ]
