# Generated by Django 5.2.3 on 2025-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Product ID",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Price ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Session ID",
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(blank=True, null=True, verbose_name="Checkout URL"),
                ),
            ],
        ),
    ]
